In [134]:
import pandas as pd
import numpy as np

In [135]:
Transactions = pd.read_excel('KPMG_VI_New_raw_data_update_final.xlsx', sheet_name='Transactions',header=1)

In [136]:
Transactions.head()

transaction_id  product_id  customer_id transaction_date  online_order  \
0               1           2         2950       2017-02-25           0.0   
1               2           3         3120       2017-05-21           1.0   
2               3          37          402       2017-10-16           0.0   
3               4          88         3135       2017-08-31           0.0   
4               5          78          787       2017-10-01           1.0   

  order_status           brand product_line product_class product_size  \
0     Approved           Solex     Standard        medium       medium   
1     Approved   Trek Bicycles     Standard        medium        large   
2     Approved      OHM Cycles     Standard           low       medium   
3     Approved  Norco Bicycles     Standard        medium       medium   
4     Approved  Giant Bicycles     Standard        medium        large   

   list_price  standard_cost  product_first_sold_date  
0       71.49          53.62                  41245.0  
1     2091.47         388.92                  41701.0  
2     1793.43         248.82                  36361.0  
3     1198.46         381.10                  36145.0  
4     1765.30         709.48                  42226.0

In [137]:
Transactions.shape

(20000, 13)

In [138]:
Transactions.transaction_id.unique() # No repetation in transaction_id col

array([    1,     2,     3, ..., 19998, 19999, 20000], dtype=int64)

In [139]:
tr_prod_id = Transactions.product_id.unique()
tr_prod_id.sort()
tr_prod_id
# 100 unique products

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int64)

In [140]:
Transactions.product_id.isna().sum() # No missing data in product_id col 
# product_id passes all requirements of Standerd Data Quality Dimensions

0

In [141]:
Transactions.online_order.unique()

array([ 0.,  1., nan])

In [142]:
Transactions.online_order.isna().sum()

360

In [143]:
Transactions.transaction_date.dtypes # Data type is correct

dtype('<M8[ns]')

In [144]:
Transactions.transaction_date.isna().sum() # Date contains no NULL values

0

In [145]:
# Checking if all date rows have same formate
# Logic credit: https://stackoverflow.com/users/2901002/jezrael
m1 = Transactions.transaction_date.eq('') | Transactions.transaction_date.isna()
m2 = pd.to_datetime(Transactions.transaction_date, errors='coerce').isna()

print (m1.eq(m2).all())

# All Date rows are correct

True


In [146]:
Transactions.order_status.unique()

array(['Approved', 'Cancelled'], dtype=object)

In [147]:
Transactions.order_status.isna().sum() # order_status contains no NULL values

0

In [148]:
Transactions.brand.unique()

array(['Solex', 'Trek Bicycles', 'OHM Cycles', 'Norco Bicycles',
       'Giant Bicycles', 'WeareA2B', nan], dtype=object)

In [149]:
Transactions.brand.isna().sum()

197

In [150]:
Transactions.product_line.unique()

array(['Standard', 'Road', 'Mountain', 'Touring', nan], dtype=object)

In [151]:
Transactions.product_line.isna().sum()

197

In [152]:
Transactions.standard_cost.isna().sum()

197

In [153]:
Transactions.product_class.unique()

array(['medium', 'low', 'high', nan], dtype=object)

In [154]:
Transactions.list_price.isna().sum()

0

In [155]:
Transactions.list_price.describe()

count    20000.000000
mean      1107.829449
std        582.825242
min         12.010000
25%        575.270000
50%       1163.890000
75%       1635.300000
max       2091.470000
Name: list_price, dtype: float64

In [156]:
Transactions.standard_cost.head()

0     53.62
1    388.92
2    248.82
3    381.10
4    709.48
Name: standard_cost, dtype: float64

In [157]:
Transactions.standard_cost.isna().sum()

197

In [158]:
Transactions.product_first_sold_date.describe()

count    19803.000000
mean     38199.776549
std       2875.201110
min      33259.000000
25%      35667.000000
50%      38216.000000
75%      40672.000000
max      42710.000000
Name: product_first_sold_date, dtype: float64

In [159]:
NewCustomerList = pd.read_excel('KPMG_VI_New_raw_data_update_final.xlsx', sheet_name='NewCustomerList',header=1)

In [160]:
NewCustomerList.head()

first_name  last_name  gender  past_3_years_bike_related_purchases  \
0    Chickie    Brister    Male                                   86   
1      Morly     Genery    Male                                   69   
2    Ardelis  Forrester  Female                                   10   
3     Lucine      Stutt  Female                                   64   
4    Melinda     Hadlee  Female                                   34   

         DOB                   job_title job_industry_category  \
0 1957-07-12             General Manager         Manufacturing   
1 1970-03-22         Structural Engineer              Property   
2 1974-08-28      Senior Cost Accountant    Financial Services   
3 1979-01-28  Account Representative III         Manufacturing   
4 1965-09-21           Financial Analyst    Financial Services   

      wealth_segment deceased_indicator owns_car  ...  state    country  \
0      Mass Customer                  N      Yes  ...    QLD  Australia   
1      Mass Customer                  N       No  ...    NSW  Australia   
2  Affluent Customer                  N       No  ...    VIC  Australia   
3  Affluent Customer                  N      Yes  ...    QLD  Australia   
4  Affluent Customer                  N       No  ...    NSW  Australia   

   property_valuation Unnamed: 16 Unnamed: 17  Unnamed: 18  Unnamed: 19  \
0                   6        0.56      0.7000       0.8750     0.743750   
1                  11        0.89      0.8900       1.1125     0.945625   
2                   5        1.01      1.0100       1.0100     1.010000   
3                   1        0.87      1.0875       1.0875     1.087500   
4                   9        0.52      0.5200       0.6500     0.650000   

   Unnamed: 20  Rank     Value  
0            1     1  1.718750  
1            1     1  1.718750  
2            1     1  1.718750  
3            4     4  1.703125  
4            4     4  1.703125  

[5 rows x 23 columns]

In [161]:
NewCustomerList.first_name.unique().shape

(940,)

In [162]:
NewCustomerList.last_name.isna().sum()

29

In [163]:
NewCustomerList.past_3_years_bike_related_purchases.describe()

count    1000.000000
mean       49.836000
std        27.796686
min         0.000000
25%        26.750000
50%        51.000000
75%        72.000000
max        99.000000
Name: past_3_years_bike_related_purchases, dtype: float64

In [164]:
NewCustomerList.isna().sum()

first_name                               0
last_name                               29
gender                                   0
past_3_years_bike_related_purchases      0
DOB                                     17
job_title                              106
job_industry_category                  165
wealth_segment                           0
deceased_indicator                       0
owns_car                                 0
tenure                                   0
address                                  0
postcode                                 0
state                                    0
country                                  0
property_valuation                       0
Unnamed: 16                              0
Unnamed: 17                              0
Unnamed: 18                              0
Unnamed: 19                              0
Unnamed: 20                              0
Rank                                     0
Value                                    0
dtype: int6

In [165]:
NewCustomerList.DOB.dtype

dtype('<M8[ns]')

In [166]:
NewCustomerList.DOB.sort_values(ascending=True) # Oldaest data 1938 Age - 82

797   1938-06-08
885   1938-06-09
769   1938-08-05
585   1938-08-30
265   1938-08-31
         ...    
775          NaT
835          NaT
883          NaT
904          NaT
984          NaT
Name: DOB, Length: 1000, dtype: datetime64[ns]

In [167]:
NewCustomerList.DOB.sort_values(ascending=False) # Data seems upto date as age of latest client is 18

354   2002-02-27
396   2002-01-17
763   2002-01-04
475   2001-12-29
996   2001-10-17
         ...    
775          NaT
835          NaT
883          NaT
904          NaT
984          NaT
Name: DOB, Length: 1000, dtype: datetime64[ns]

In [168]:
NewCustomerList.DOB.isna().sum()

17

In [169]:
NewCustomerList.job_industry_category.unique() # Categorical series | Looks okay

array(['Manufacturing', 'Property', 'Financial Services', 'Entertainment',
       'Retail', 'IT', 'Telecommunications', 'Health', nan, 'Argiculture'],
      dtype=object)

In [170]:
NewCustomerList.job_industry_category.isna().sum()

165

In [171]:
NewCustomerList.wealth_segment.unique()

array(['Mass Customer', 'Affluent Customer', 'High Net Worth'],
      dtype=object)

In [172]:
NewCustomerList.wealth_segment.isna().sum()

0

In [173]:
NewCustomerList.deceased_indicator.unique()

array(['N'], dtype=object)

In [174]:
NewCustomerList.deceased_indicator.isna().sum()

0

In [175]:
NewCustomerList.owns_car.unique()

array(['Yes', 'No'], dtype=object)

In [176]:
NewCustomerList.owns_car.isna().sum()

0

In [177]:
CustomerDemographic = pd.read_excel('KPMG_VI_New_raw_data_update_final.xlsx', sheet_name='CustomerDemographic',header=1)

In [178]:
CustomerDemographic.head()

customer_id      first_name  last_name  gender  \
0            1         Laraine  Medendorp       F   
1            2             Eli    Bockman    Male   
2            3           Arlin     Dearle    Male   
3            4          Talbot        NaN    Male   
4            5  Sheila-kathryn     Calton  Female   

   past_3_years_bike_related_purchases        DOB               job_title  \
0                                   93 1953-10-12     Executive Secretary   
1                                   81 1980-12-16  Administrative Officer   
2                                   61 1954-01-20      Recruiting Manager   
3                                   33 1961-10-03                     NaN   
4                                   56 1977-05-13           Senior Editor   

  job_industry_category     wealth_segment deceased_indicator  \
0                Health      Mass Customer                  N   
1    Financial Services      Mass Customer                  N   
2              Property      Mass Customer                  N   
3                    IT      Mass Customer                  N   
4                   NaN  Affluent Customer                  N   

                                             default owns_car  tenure  
0                                                 "'      Yes    11.0  
1                       <script>alert('hi')</script>      Yes    16.0  
2                                2018-02-01 00:00:00      Yes    15.0  
3  () { _; } >_[$($())] { touch /tmp/blns.shellsh...       No     7.0  
4                                                NIL      Yes     8.0

In [179]:
CustomerDemographic.isna().sum()

customer_id                              0
first_name                               0
last_name                              125
gender                                   0
past_3_years_bike_related_purchases      0
DOB                                     87
job_title                              506
job_industry_category                  656
wealth_segment                           0
deceased_indicator                       0
default                                302
owns_car                                 0
tenure                                  87
dtype: int64

In [180]:
CustomerDemographic.gender.unique()

array(['F', 'Male', 'Female', 'U', 'Femal', 'M'], dtype=object)

In [181]:
CustomerDemographic.past_3_years_bike_related_purchases.max()

99

In [182]:
CustomerDemographic.past_3_years_bike_related_purchases.min()

0

In [183]:
CustomerDemographic.past_3_years_bike_related_purchases.dtype # No decemal value or illegal value

dtype('int64')

In [184]:
CustomerDemographic.DOB.sort_values()

33     1843-12-21
719    1931-10-23
1091   1935-08-22
3409   1940-09-22
2412   1943-08-11
          ...    
3778          NaT
3882          NaT
3930          NaT
3934          NaT
3997          NaT
Name: DOB, Length: 4000, dtype: datetime64[ns]

In [185]:
CustomerDemographic.job_industry_category.unique() # same categories in both CustomerDemographic and NewCustomerList

array(['Health', 'Financial Services', 'Property', 'IT', nan, 'Retail',
       'Argiculture', 'Manufacturing', 'Telecommunications',
       'Entertainment'], dtype=object)

In [186]:
CustomerDemographic.wealth_segment.unique()

array(['Mass Customer', 'Affluent Customer', 'High Net Worth'],
      dtype=object)

In [187]:
CustomerDemographic.deceased_indicator.unique()

array(['N', 'Y'], dtype=object)

In [188]:
CustomerDemographic.owns_car.unique()

array(['Yes', 'No'], dtype=object)

In [189]:
CustomerDemographic.owns_car.isna().sum()

0

In [190]:
CustomerDemographic.tenure.dtype

dtype('float64')

In [191]:
CustomerDemographic.tenure.isna().sum()

87

In [193]:
CustomerDemographic.tenure.min()

1.0

In [194]:
CustomerDemographic.tenure.max()

22.0

In [196]:
CustomerDemographic.default.dtype

dtype('O')

In [197]:
CustomerAddress = pd.read_excel('KPMG_VI_New_raw_data_update_final.xlsx', sheet_name='CustomerAddress',header=1)

In [198]:
CustomerAddress.head()

customer_id              address  postcode            state    country  \
0            1   060 Morning Avenue      2016  New South Wales  Australia   
1            2  6 Meadow Vale Court      2153  New South Wales  Australia   
2            4   0 Holy Cross Court      4211              QLD  Australia   
3            5  17979 Del Mar Point      2448  New South Wales  Australia   
4            6     9 Oakridge Court      3216              VIC  Australia   

   property_valuation  
0                  10  
1                  10  
2                   9  
3                   4  
4                   9

In [200]:
CustomerAddress.isna().sum()

customer_id           0
address               0
postcode              0
state                 0
country               0
property_valuation    0
dtype: int64

In [201]:
CustomerAddress.customer_id.unique()

array([   1,    2,    4, ..., 4001, 4002, 4003], dtype=int64)

In [205]:
CustomerAddress.customer_id.value_counts()>1

2047    False
653     False
2728    False
677     False
2724    False
        ...  
3371    False
1322    False
3367    False
1318    False
2049    False
Name: customer_id, Length: 3999, dtype: bool

In [207]:
CustomerAddress.address.dtype

dtype('O')

In [208]:
CustomerAddress.postcode.dtype

dtype('int64')

In [209]:
CustomerAddress.state.unique()

array(['New South Wales', 'QLD', 'VIC', 'NSW', 'Victoria'], dtype=object)

In [210]:
CustomerAddress.country.unique()

array(['Australia'], dtype=object)

In [211]:
CustomerAddress.property_valuation.dtype

dtype('int64')

In [212]:
CustomerAddress.property_valuation.max()

12

In [213]:
CustomerAddress.property_valuation.min()

1